# Generated by Django 4.0.6 on 2022-08-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_alter_comentarios_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='domicilio',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='telefono',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
